---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package in ubuntu
    package:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install httpd and php package in RH/CentOS
    package:
      name:
      - httpd
      - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Amazon"

