---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates RH/CentOS
    tags: always
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"
  - name: install updates Ubuntu
    tags: always
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
- hosts: web_servers
  tasks:

  - name: install apache2 and php package in ubuntu
    tags: apache,apache2,ubuntu
    package:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  - name: install httpd and php package in RH/CentOS
    tags: apache,httpd,centos
    package:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "Amazon"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb in CentOS
    tags: centos,db,mariadb
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name: install mariadb in Ubuntu
    tags: db,mariadb,ubuntu
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba in CentOS or Ubuntu
    tags: samba
    package:
      name: samba
      state: latest
    when: ansible_distribution == ["Amazon", "Ubuntu"]

